name: Swift

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: xcodebuild clean build -workspace Smartpad-macOS/Smartpad-macOS.xcodeproj/project.xcworkspace -scheme Smartpad-macOS CODE_SIGN_IDENTITY=-
      - name: Test
        run: xcodebuild clean test -workspace Smartpad-macOS/Smartpad-macOS.xcodeproj/project.xcworkspace -scheme Smartpad-macOS CODE_SIGN_IDENTITY=-
